apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/benkason/argocd.git
    targetRevision: HEAD
    path: argocd_deploy
  destination:
    server: https://kubernetes.default.svc
    namespace: lab
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
    
